# gateway-service:
#   timeout-ms: 3000
#   failure-rate-threshold: 50
#   slow-call-rate-threshold: 50
#   slow-call-duration-threshold: 50
#   permitted-num-of-calls-in-half-open-state: 10
#   sliding-window-size: 10
#   min-number-of-calls: 10
#   wait-duration-in-open-state: 60000
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health, info
        # include: health, info, circuitbreakers
# management:
#   endpoints:
#     web:
#       base-path: /actuator
#       exposure.include: health, gateway
#   endpoint:
#     health:
#       show-details: always
#     prometheus:
#       cache.time-to-live: 1ms
#     gateway:
#       enabled: true
server:
  port: 9096
spring:
  application:
    name: API-GATEWAY
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: VISIT-QUERY-MS
          uri: lb://VISIT-QUERY-MS
          predicates:
            - Path=/visitQuery/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: visitQueryService1CircuitBreaker
                fallbackUri: forward:/fallback/visit-query-fallback
        - id: VISIT-CMD-MS
          uri: lb://VISIT-CMD-MS
          predicates:
            - Path=/visitCmd/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: visitCmdService1CircuitBreaker
                fallbackUri: forward:/fallback/visit-cmd-fallback
        - id: LABORATORY-CMD-MS
          uri: lb://LABORATORY-CMD-MS
          predicates:
            - Path=/laboratoryCmd/test/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: labCmdService1CircuitBreaker
                fallbackUri: forward:/fallback/lab-cmd-fallback
        - id: LABORATORY-QUERY-MS
          uri: lb://LABORATORY-QUERY-MS
          predicates:
            - Path=/laboratoryQuery/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: labQueryService1CircuitBreaker
                fallbackUri: forward:/fallback/lab-query-fallback
        - id: PHARMACY-CMD-MS1
          uri: lb://PHARMACY-CMD-MS
          predicates:
            - Path=/medicineRequestCmd/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: pharmacyCmdService1CircuitBreaker
                fallbackUri: forward:/fallback/pharmacy-cmd-fallback
        - id: PHARMACY-CMD-MS2
          uri: lb://PHARMACY-CMD-MS
          predicates:
            - Path=/medicineCmd/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: pharmacyCmdService2CircuitBreaker
                fallbackUri: forward:/fallback/pharmacy-cmd-fallback
        - id: PHARMACY-QUERY-MS1
          uri: lb://PHARMACY-QUERY-MS
          predicates:
            - Path=/medicineQuery/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: pharmacyQueryService1CircuitBreaker
                fallbackUri: forward:/fallback/pharmacy-query-fallback
        - id: PHARMACY-QUERY-MS2
          uri: lb://PHARMACY-QUERY-MS
          predicates:
            - Path=/medicineRequestQuery/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: pharmacyQueryService2CircuitBreaker
                fallbackUri: forward:/fallback/pharmacy-query-fallback
        - id: RECEPTION-QUERY-MS
          uri: lb://RECEPTION-QUERY-MS
          predicates:
            - Path=/api/receptionQueries/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: receptionQueryServiceCircuitBreaker
                fallbackUri: forward:/fallback/reception-query-fallback
        - id: RECEPTION-CMD-MS
          uri: lb://RECEPTION-CMD-MS
          predicates:
            - Path=/receptionCmd/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: receptionCmdServiceCircuitBreaker
                fallbackUri: forward:/fallback/reception-cmd-fallback
        - id: PATIENT-CMD-MS
          uri: lb://PATIENT-CMD-MS
          predicates:
            - Path=/patient/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            - name: CircuitBreaker
              args:
                name: patientCmdServiceCircuitBreaker
                fallbackUri: forward:/fallback/patient-cmd-fallback
        - id: PATIENT-QUERY-MS
          uri: lb://PATIENT-QUERY-MS
          predicates:
            - Path=/api/patientQueries/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10
                key-resolver: "#{@authHeaderResolver}"
            # - name: CircuitBreaker
            #   args:
            #     name: patientQueryServiceCircuitBreaker
            #     fallbackUri: forward:/fallback/patient-query-fallback
