server:
  port: 8081
spring:
  application:
    name: PATIENT-CMD-MS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak-docker-compose:8080/realms/hisclientapp/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://mysql-docker-compose:3306/patient_db?createDatabaseIfNotExist=true
    username: root
    password: myhawramRootPsw1
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    # defer-datasource-initialization: true
    show-sql: true
axon:
  axonserver:
    servers: axon-docker-compose:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson
