server:
  port: 8082
spring:
  application:
    name: PATIENT-QUERY-MS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/hisclientapp/protocol/openid-connect/certs
  datasource:
    url: jdbc:mysql://localhost:3306/patient_db?createDatabaseIfNotExist=true
    username: root
    password: myhawramRootPsw1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
axon:
  axonserver:
    servers: localhost:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson
