server:
  port: 9095
spring:
  application:
    name: PHARMACY-QUERY-MS
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacy_db?createDatabaseIfNotExist=true
    username: root
    password: myhawramRootPsw1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
