server:
  port: 8092
spring:
  application:
    name: VISIT-QUERY-MS
  datasource:
    url: jdbc:mysql://localhost:3306/visit_db?createDatabaseIfNotExist=true
    username: root
    password: myhawramRootPsw1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
