server:
  port: 8092
spring:
  application:
    name: VISIT-QUERY-MS
  datasource:
    url: jdbc:mysql://mysql-docker-compose:3306/visit_db?createDatabaseIfNotExist=true
    username: root
    password: myhawramRootPsw1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
axon:
  axonserver:
    servers: axon-docker-compose:8124
  serializer:
    general: jackson
    events: jackson
    messages: jackson
